name: Build GalaxyTimer (PyInstaller with GUI settings)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    timeout-minutes: 90
    env:
      PYTHON_VERSION: '3.10'
      ENTRY: pyscript/galaxytimer.py  # 确保路径准确

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Upgrade pip & install build tools
        shell: pwsh
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install pyinstaller pyttsx3 PySide6 keyboard  # 确保对 keyboard 的版本升级

      - name: Prepare build_src (copy sources + resources)
        shell: pwsh
        run: |
          Remove-Item -Force -ErrorAction SilentlyContinue .\GalaxyTimer.exe
          Remove-Item -Recurse -Force -ErrorAction SilentlyContinue .\build_src, .\obf, .\dist, .\build

          New-Item -ItemType Directory -Force -Path build_src | Out-Null
          Copy-Item -Recurse -Force -Path .\pyscript -Destination .\build_src\pyscript

          $srcFolders = @("logic", "core", "widgets")
          foreach ($folder in $srcFolders) {
            if (Test-Path ".\pyscript\$folder") {
              Copy-Item -Recurse -Force -Path ".\pyscript\$folder" -Destination ".\build_src\pyscript\$folder"
            } else {
              Write-Host "Warning: Folder pyscript\$folder not found."
            }
          }

      - name: Inject build salt (optional)
        shell: pwsh
        run: |
          $bytes = New-Object byte[] 12
          $rng = New-Object System.Security.Cryptography.RNGCryptoServiceProvider
          $rng.GetBytes($bytes)
          $salt = [System.Convert]::ToBase64String($bytes) -replace '/','_' -replace '\+','-' -replace '=',''
          if ($salt.Length -gt 16) { $salt = $salt.Substring(0,16) }
          Write-Host "Generated SALT: $salt"
          Add-Content -Path $env:GITHUB_ENV -Value "BUILD_SALT=$salt"

          $entryPath = Join-Path -Path (Get-Location) -ChildPath $env:ENTRY
          (Get-Content $entryPath -Raw) -replace "__BUILD_SALT__", $salt | Set-Content $entryPath -Encoding UTF8

      - name: Build with PyInstaller
        shell: pwsh
        run: |
          $iconPath = ".\resources\icon\icon.ico"
          if (-not (Test-Path $iconPath)) {
            Write-Host "Icon not found, continuing without setting an icon."
            pyinstaller --noconfirm --windowed --onefile --hidden-import=pyttsx3 --hidden-import=PySide6 --hidden-import=keyboard --add-data "build_src\pyscript\logic;logic" --add-data "build_src\pyscript\core;core" --add-data "build_src\pyscript\widgets;widgets" $env:ENTRY
          } else {
            pyinstaller --noconfirm --windowed --onefile --hidden-import=pyttsx3 --hidden-import=PySide6 --hidden-import=keyboard --icon=$iconPath --add-data "build_src\pyscript\logic;logic" --add-data "build_src\pyscript\core;core" --add-data "build_src\pyscript\widgets;widgets" $env:ENTRY
          }

      - name: Rename and publish exe
        shell: pwsh
        run: |
          $exePath = Join-Path -Path (Get-Location) -ChildPath "dist\galaxytimer.exe"
          if (Test-Path $exePath) {
            Move-Item -Force $exePath .\GalaxyTimer.exe
            Write-Host "Moved to GalaxyTimer.exe"
          } else {
            Write-Error "GalaxyTimer.exe not found in the dist directory."
          }

      - name: Clean intermediate files (optional)
        shell: pwsh
        run: |
          Remove-Item -Recurse -Force -ErrorAction SilentlyContinue .\dist, .\build
          Get-ChildItem -Path . -Filter "*.spec" -File | ForEach-Object { Remove-Item -Force $_.FullName }

      - name: Upload GalaxyTimer.exe artifact
        uses: actions/upload-artifact@v4
        with:
          name: GalaxyTimer-exe
          path: SaveGalaxyTimer.exe
